// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtspPlLh5bgPtlj6uQ7tjCZkF0ppLuWpA',
    appId: '1:223459765519:web:c863bfce888300baa6a27a',
    messagingSenderId: '223459765519',
    projectId: 'wordologyapp-a6698',
    authDomain: 'wordologyapp-a6698.firebaseapp.com',
    storageBucket: 'wordologyapp-a6698.appspot.com',
    measurementId: 'G-RP13VBPTTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdfZj1iwOoCDob_poSg0uUNF1G0H-7joc',
    appId: '1:223459765519:android:00c43bfe352c8b82a6a27a',
    messagingSenderId: '223459765519',
    projectId: 'wordologyapp-a6698',
    storageBucket: 'wordologyapp-a6698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5bfgNr9LGXYAqIudAAX8iHO0D3at2_TU',
    appId: '1:223459765519:ios:063d7f67ff150ac9a6a27a',
    messagingSenderId: '223459765519',
    projectId: 'wordologyapp-a6698',
    storageBucket: 'wordologyapp-a6698.appspot.com',
    iosBundleId: 'com.codingminds.wordologyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5bfgNr9LGXYAqIudAAX8iHO0D3at2_TU',
    appId: '1:223459765519:ios:96cfe3093fa89d3ba6a27a',
    messagingSenderId: '223459765519',
    projectId: 'wordologyapp-a6698',
    storageBucket: 'wordologyapp-a6698.appspot.com',
    iosBundleId: 'com.codingminds.wordologyApp.RunnerTests',
  );
}
